apiVersion: v1
kind: Pod
metadata:
  name: firstpod
spec:
  containers:
    - name: webservers 
      image: nginx
  initContainers:
    - name: webserverinit
      image: nginx
      args: [ "sleep" , "50" ]
