apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs 
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
    # tier: frontend
    # tier: dev
      env: dev
  template:
    metadata:
      labels:
       #tier: frontend
       #tier: dev
        env: dev
    spec:
      containers:
      - name: nginx-server 
        image: nginx:1
