apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-t4-1
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
  tolerations:
     - key: ""
       operator: "Exists" 
       effect: "NoExecute" 
      # value: "minion1"
