apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-5
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
  tolerations:
     - key: "name"
       operator: "Equal"
       effect: "NoSchedule"
       value: "minion1"
       tolerationSeconds: 60
