apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
   - default:
      memory: 256Mi
     defaultRequest:
      memory: 128Mi
   -maxLimitRequestRatio:
      memory: 3

    type: Container
