apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
spec:
  limits:
  - default:
      memory: 256Mi
   -maxLimitRequestRatio:
      memory: 3
    defaultRequest:
      memory: 128Mi
    type: Container

