apiVersion: v1
kind: Service
metadata:
  name: my-service-qc
spec:
  type: ClusterIP
  selector:
    env: dev
  ports:
    - port: 443
      targetPort: 80
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
