apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-homee
          mountPath: /var/jenkins_homee
      volumes:
      - name: jenkins-homee
        emptyDir: { }
