apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-single-value
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      env:
       - name: new-value
         valueFrom:
           configMapKeyRef:
             key: Name
             name: cm-from-env   
