apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-multiple-values
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      envFrom:
       - configMapRef: 
          name: cm-from-env   
