apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-as-file
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      volumeMounts:
       - name: test
         mountPath: "/config"
         readOnly: true
      envFrom:
       - secretRef: 
          name: secret-from-env   
  volumes:
   - name: test
     secret:
        name: secret-from-env
