apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-as-file
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      volumeMounts:
       - name: test
         mountPath: "/config"
         readOnly: true
  volumes:
   - name: test
     configMap:
        name: cm-from-env
        items:
        - key: Name
          path: keys
