apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-single-value
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      env:
       - name: new-value
         valueFrom:
           SecretKeyRef:
             key: Name
             name: secret-from-env   
