apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-as-file
  labels:
    env: prod  
spec:
  containers:
    - name: webservers 
      image: nginx
      volumeMounts:
       - name: test
         mountPath: "/config"
         readOnly: true
    # envFrom:
    #  - configMapRef: 
    #     name: cm-from-env   
  volumes:
   - name: test
     configMap:
        name: cm-from-env
